### ISSUE TITLE
出现问题；There is a problem

### ISSUE THREAD

**Issue by kunpeng9** [k-kirill/anki-libunity#2]
错误 
有一个错误发生了.请在按住shift键的同时启动Anki，这样可以临时的禁用您已经安装的插件。 
如果仅仅是因为插件引起的问题，请选择工具>插件菜单项来将出错的的插件设置成失效，然后重启Anki，重复以上的步骤直到你发现了具体是哪个插件引起的问题。 
当你已经发现是因为插件引起的问题，请在我们的支持网站上 [插件支持](https://help.ankiweb.net/discussions/add-ons/) 上报告问题。 
调试信息：
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=?
Add-ons, last update check: 2020-11-01 16:55:03

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 53, in handler
  File "aqt\main.py", line 143, in on_window_init
  File "aqt\gui_hooks.py", line 1730, in __call__
  File "C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\901237400\__init__.py", line 7, in set_progress
    due_card_count = len(mw.col.find_cards("is:new or is:due"))
AttributeError: 'NoneType' object has no attribute 'find_cards'
-
901237400应该是这个插件的问题吧；901237400 should be the problem of this plug-in;
![image](https://user-images.githubusercontent.com/44609485/97820270-5fca0e80-1ce8-11eb-8731-35334f02600f.png)
-
Anki 2.1.35（84dcaa86）Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
平台：Windows 10
标志：frz=True ao=True sv=？
附加组件，上次更新检查：2020-11-01 16:55:03
捕获到异常：
回溯（最近一次呼叫）：
文件“aqt\进度.py，第53行，在处理程序中
文件“aqt\主.py“，第143行，on_window_init中
文件“aqt\gui”_钩子.py“，第1730行，in\u call__
文件“C:\Users\YEDONG\AppData\Roaming\Anki2\addons21\901237400\\u init_u.py”，第7行，在set_progress中
due_card_count=长度(中校查找卡（“是新的还是到期的）
AttributeError:“NoneType”对象没有“find\u cards”属性

**Comment by k-kirill** [comment]
Hi. Sorry, but the add-on supports only Linux (Windows and macOS are not supported) and only the panels/docks that support libunity.
As to the exception itself it has been fixed in #1
