### ISSUE TITLE
Fails to install on anki 2.1 on Debian 10

### ISSUE THREAD

**Issue by KublaiKhan64** [k-kirill/anki-libunity#3]
I don't have much info except that anki refuses to install the addon:

One or more errors occurred:

901237400: Invalid code, or add-on not available for your version of Anki. If there's any dependencies I need let me know

 OS: Debian GNU/Linux 10 (buster) x86_64 
Host: MS-7A38 8.0 
Kernel: 4.19.0-12-amd64 
Packages: 2406 (dpkg), 37 (flatpak) 
Shell: bash 5.0.3 
DE: GNOME 3.30.2 
CPU: AMD Ryzen 5 3600 6- (12) @ 4.200GHz 
GPU: AMD ATI Radeon RX 470/480 
Memory: 6404MiB / 16052MiB

**Comment by k-kirill** [comment]
Could you please clarify what is the exact version of Anki you are using? I can lower the min required version from 2.1.35 to whatever version it makes sense.

**Comment by KublaiKhan64** [comment]
> Could you please clarify what is the exact version of Anki you are using? I can lower the min required version from 2.1.35 to whatever version it makes sense.

Version 2.1.22 (0ecc189a)

**Comment by k-kirill** [comment]
I've updated the min version to 2.1.0. Can you please recheck it?
Also, I use [the Flatpak Anki app](https://flathub.org/apps/details/net.ankiweb.Anki), which means its desktop file should be named `net.ankiweb.Anki.desktop`.

**Comment by KublaiKhan64** [comment]
I got it installed but now it gives me this issue when starting anki

When loading '⁨Anki libunity Linux only⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 208, in loadAddons
  File "/home/william/.local/share/Anki2/addons21/901237400/__init__.py", line 3, in <module>
    from PyQt5 import QtDBus, QtCore
ImportError: cannot import name 'QtDBus' from 'PyQt5' (/usr/local/share/anki/bin/PyQt5/__init__.pyc)

**Comment by k-kirill** [comment]
Looks like you use some strange Anki installation with incomplete embedded PyQt5 libraries. Therefore, I suggest you switch to [the Flatpak Anki app](https://flathub.org/apps/details/net.ankiweb.Anki) to avoid issues with missing, incompatible or incomplete dependencies.
If you want to try to make your installation work then please explain how you installed Anki.
