### ISSUE TITLE
No due cards in panel also after floating notifications disappear they don't appear when I click the notification tray icon

### ISSUE THREAD

**Issue by ghost** [k-kirill/anki-libunity#5]
![image](https://user-images.githubusercontent.com/44734407/106386318-a35e1280-63d4-11eb-8a09-85dbe0b89403.png)
I have the addon installed but the number of due cards dosen't appear on the panel. I am using KDE manjaro, it's the default panel.

The notification that appears after a new card is available appears but it dosen't stay in the notification center.

Also the number of cards to study seems wrong it says over 30 thousand when I have 500 due

**Comment by k-kirill** [comment]
Thanks for the report.
1. What's the name of your Anki .desktop file? If it isn't `net.ankiweb.Anki.desktop`, but, for example, `anki.desktop`, then please change the application name in the add-on's config to `anki`.
2. In GNOME it disappears when you focus Anki window, could you please double check that it disappears before you switch to Anki window?
3. The number is the sum of all the new and due cards. I guess it can be wrong if you have too many new cards. Is it the case for you?

**Comment by ghost** [comment]
I did change it to anki.desktop in addons->addon->config

On KDE it dosen't disappear when I focus on anki, there is a set amount of time the notification runs. That's not the problem. The problem is that after they dissapear they don't appear here 
![image](https://user-images.githubusercontent.com/44734407/106391675-cf868d00-63ee-11eb-95ca-a10c7facd5fc.png)

I have 180 new cards and 600 reviews.

**Comment by k-kirill** [comment]
1. It should be just `anki` as it is used to find both the desktop file and the icon file.
2. Sorry, I don't know how KDE Plasma works with notifications. In the code I set `expire_timeout` to -1, which means the following according to [the specs](https://specifications.freedesktop.org/notification-spec/latest/ar01s09.html)
> the notification's expiration time is dependent on the notification server's settings
3. The query I use to find the number of the cards to study is `is:new or is:due`, does it return 30k cards in your Anki browser?

**Comment by ghost** [comment]
yes if I press b it returns around 30k cards. It shows every unseen card as new. I am only going to learn maybe 20 of those 30k unseen cards. I think a better way to go about it is just to query is:due

Yup changing it to just anki in the settings fixed the problem
